config/routes.rb
Rails.application.routes.draw do
  resources :user_vacancies

  resources :vacancies

  resources :occupations

  resources :projects

  resources :jobs

  resources :analytics

  devise_for :users

  resources :users, only: [:show]

  devise_scope :user do
    authenticated :user do
      root :to => 'projects#index'
    end
    unauthenticated :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :vacancies do
    post 'apply', on: :member
  end

  resources :user_vacancies do
    post 'approve', on: :member
  end

  resources :user_vacancies do
    post 'disapprove', on: :member
  end

end

app/models/occupation.rb
class Occupation < ActiveRecord::Base
	#associations
	has_many :users
	has_many :vacancies

	#validations
	validates :name, :description, presence: true
	validates :name, length: { in: 2..120 }, uniqueness: true
	validates :description, length: { in: 2..200 }

end

app/controllers/occupations_controller.rb
class OccupationsController < ApplicationController
  before_action :set_occupation, only: [:show, :edit, :update, :destroy]
  before_action :verify_priority, only: [:create, :update, :index]
  before_action :verify_session

  # GET /occupations
  # GET /occupations.json
  def index
    @occupations = Occupation.all
  end

  # GET /occupations/1
  # GET /occupations/1.json
  def show
  end

  # GET /occupations/new
  def new
    @occupation = Occupation.new
  end

  # GET /occupations/1/edit
  def edit
  end

  # POST /occupations
  # POST /occupations.json
  def create
    @occupation = Occupation.new(occupation_params)

    respond_to do |format|
      if @occupation.save
        format.html { redirect_to @occupation, notice: 'Ocupación creada correctamente.' }
        format.json { render :show, status: :created, location: @occupation }
      else
        format.html { render :new }
        format.json { render json: @occupation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /occupations/1
  # PATCH/PUT /occupations/1.json
  def update
    respond_to do |format|
      if @occupation.update(occupation_params)
        format.html { redirect_to @occupation, notice: 'Ocupación actualizada correctamente.' }
        format.json { render :show, status: :ok, location: @occupation }
      else
        format.html { render :edit }
        format.json { render json: @occupation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /occupations/1
  # DELETE /occupations/1.json
  def destroy
    @occupation.destroy
    respond_to do |format|
      format.html { redirect_to occupations_url, notice: 'Ocupación eliminada correctamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_occupation
      @occupation = Occupation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def occupation_params
      params.require(:occupation).permit(:name, :description)
    end
end

app/helpers/occupations_helper.rb
module OccupationsHelper
end

app/views/occupations/_form.html.erb
<%= form_for(@occupation) do |f| %>
  <% if @occupation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@occupation.errors.count, "error") %> prohibited this occupation from being saved:</h2>

      <ul>
      <% @occupation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :descripción %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit "Guardar", class: "btn btn-info"  %>
  </div>
<% end %>

app/views/occupations/edit.html.erb
<h1>Editar Ocupación</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @occupation, class: "btn btn-small btn-success btn-xs" %> |
<%= link_to 'Atrás', occupations_path, class: "btn btn-small btn-danger btn-xs" %>

app/views/occupations/index.html.erb
<%= image_tag('logo.jpg')%>
<p id="notice"><%= notice %></p>

<h1>Ocupaciones</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripci&oacute;n</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @occupations.each do |occupation| %>
      <tr>
        <td><%= occupation.name %></td>
        <td><%= occupation.description %></td>
        <td><%= link_to 'Detalle', occupation, class: "btn btn-success" %></td>
        <td><%= link_to 'Editar', edit_occupation_path(occupation), class: "btn btn-warning" %></td>
        <td><%= link_to 'Eliminar', occupation, method: :delete, data: { confirm: '¿Eliminar Ocupación?' }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva Ocupación', new_occupation_path, class: "btn btn-small btn-success" %>

app/views/occupations/new.html.erb
<h1>Nueva Ocupación</h1>

<%= render 'form' %>

<%= link_to 'Atrás', occupations_path, class: "btn btn-small btn-danger btn-xs" %>

app/views/occupations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @occupation.name %>
</p>

<p>
  <strong>Descripción:</strong>
  <%= @occupation.description %>
</p>

<%= link_to 'Editar', edit_occupation_path(@occupation), class: "btn btn-small btn-warning btn-xs" %> |
<%= link_to 'Atrás', occupations_path, class: "btn btn-small btn-danger btn-xs" %>