config/routes.rb
Rails.application.routes.draw do
  resources :user_vacancies

  resources :vacancies

  resources :occupations

  resources :projects

  resources :jobs

  resources :analytics

  devise_for :users

  resources :users, only: [:show]

  devise_scope :user do
    authenticated :user do
      root :to => 'projects#index'
    end
    unauthenticated :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :vacancies do
    post 'apply', on: :member
  end

  resources :user_vacancies do
    post 'approve', on: :member
  end

  resources :user_vacancies do
    post 'disapprove', on: :member
  end

end

app/models/vacancy.rb
class Vacancy < ActiveRecord::Base
	#associations
	has_many :user_vacancies
	belongs_to :project
	belongs_to :occupation

	#validations
	validates :occupation_id, :project_id, :description, :hourly_wage, :hours_required, :availability_status, presence: true
	validates :description, length: { in: 2..200 }
	validates :hourly_wage, numericality: { greater_than_or_equal_to: 0 }
	validates :hours_required, numericality: { greater_than_or_equal_to: 0 }

end

app/controllers/vacancies_controller.rb
class VacanciesController < ApplicationController
  before_action :set_vacancy, only: [:show, :edit, :update, :destroy, :apply]
  helper_method :apply
  before_action :verify_session
  before_action :verify_ownership, only: [:edit, :update, :destroy]

  # GET /vacancies
  # GET /vacancies.json
  def index

    @vacancies = Vacancy.where("projects.user_id = ?", current_user.id).joins(:project)
  end

  # GET /vacancies/1
  # GET /vacancies/1.json
  def show

  end

  def apply
    if UserVacancy.where("user_vacancies.user_id = ? AND user_vacancies.vacancy_id = ?", current_user.id, @vacancy.id).empty?
      @user_vacancy = UserVacancy.new()
      @user_vacancy.user_id = current_user.id
      @user_vacancy.vacancy_id = @vacancy.id
      @user_vacancy.acceptance_status = 0
      @user_vacancy.save
    end
  end
  
  # GET /vacancies/new
  def new
    @vacancy = Vacancy.new
  end

  # GET /vacancies/1/edit
  def edit
  end

  # POST /vacancies
  # POST /vacancies.json
  def create
    @vacancy = Vacancy.new(vacancy_params)

    respond_to do |format|
      if @vacancy.save
        format.html { redirect_to @vacancy, notice: 'Vacante creada correctamente.' }
        format.json { render :show, status: :created, location: @vacancy }
      else
        format.html { render :new }
        format.json { render json: @vacancy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vacancies/1
  # PATCH/PUT /vacancies/1.json
  def update
    respond_to do |format|
      if @vacancy.update(vacancy_params)
        format.html { redirect_to @vacancy, notice: 'Vacante actualizada correctamente.' }
        format.json { render :show, status: :ok, location: @vacancy }
      else
        format.html { render :edit }
        format.json { render json: @vacancy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vacancies/1
  # DELETE /vacancies/1.json
  def destroy
    @vacancy.destroy
    respond_to do |format|
      format.html { redirect_to vacancies_url, notice: 'Vacante eliminada correctamente.' }
      format.json { head :no_content }
    end
  end

  def verify_ownership
    if current_user.id != User.select("users.id").where("vacancies.id = ?", @vacancy.id).joins('INNER JOIN projects ON projects.user_id = users.id INNER JOIN vacancies ON vacancies.project_id = projects.id').pluck(:id)[0]
      redirect_to root_url, :notice => "No eres el creador de esta vacante."
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vacancy
      @vacancy = Vacancy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vacancy_params
      params.require(:vacancy).permit(:occupation_id, :project_id, :description, :hourly_wage, :hours_required, :availability_status)
    end
end

app/helpers/vacancies_helper.rb
module VacanciesHelper
end

app/views/vacancies/_form.html.erb
<%= form_for(@vacancy) do |f| %>
  <% if @vacancy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vacancy.errors.count, "error") %> prohibited this vacancy from being saved:</h2>

      <ul>
      <% @vacancy.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ocupación %><br>
    <%= collection_select(:vacancy, :occupation_id, Occupation.all, :id, :name, {}, {:multiple => false}) %>
  </div>
  <div class="field">
    <%= f.label :proyecto%><br>
    <%= collection_select(:vacancy, :project_id, Project.where("projects.user_id = ? AND projects.availability_status = ?", current_user.id, 1), :id, :name, {}, {:multiple => false}) %>
  </div>
  <div class="field">
    <%= f.label :descripción %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :salario_por_hora %><br>
    <%= f.text_field :hourly_wage %>
  </div>
  <div class="field">
    <%= f.label :horas_requeridas %><br>
    <%= f.text_field :hours_required %>
  </div>
  <div class="field">
    <%= f.label :estatus %><br>
    <%= f.select :availability_status, [['Activo','1'],['Inactivo','0']] %>
  </div>
  <div class="actions">
   <%= f.submit "Guardar", class: "btn btn-info"  %>
  </div>
<% end %>

app/views/vacancies/apply.html.erb
Gracias por aplicar!<br>
<%= link_to 'Atrás', vacancies_path, class: "btn btn-danger btn-xs" %>

app/views/vacancies/edit.html.erb
<h1>Editar Vacante</h1>

<%= render 'form' %>
<br>
<%= link_to 'Mostrar', @vacancy,  class: "btn btn-success  btn-xs"  %> |
<%= link_to 'Atrás', vacancies_path,  class: "btn btn-danger btn-xs"  %>

app/views/vacancies/index.html.erb
<%= image_tag('logo.jpg')%>
<p id="notice"><%= notice %></p>

<h1>Mis Vacantes</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>N&uacute;mero de vacante</th>
      <th>Ocupaci&oacute;n</th>
      <th>Proyecto</th>
      <th>Descripci&oacute;n</th>
      <th>Salario por Hora</th>
      <th>Horas Requeridas</th>
      <th>Disponibilidad</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vacancies.each do |vacancy| %>
      <tr>
        <td><%= vacancy.id %></td>
        <td><%= Occupation.find_by_id(vacancy.occupation_id).name %></td>
        <td><%= Project.find_by_id(vacancy.project_id).name %></td>
        <td><%= vacancy.description %></td>
        <td><%= vacancy.hourly_wage %></td>
        <td><%= vacancy.hours_required %></td>
        <td>
          <% if vacancy.availability_status == 1%>
            <% result = "Disponible" %>
          <% else %>
            <% result = "No Disponible"%>
          <% end %>
          <%= result %>
        </td>
        <td><%= link_to 'Detalle', vacancy, class: "btn btn-success" %></td>
        <td><%= link_to 'Editar', edit_vacancy_path(vacancy), class: "btn btn-warning" %></td>
        <td><%= link_to 'Eliminar', vacancy, method: :delete, data: { confirm: '¿Eliminar la vacante?' }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva Vacante', new_vacancy_path, class: "btn btn-small btn-success" %>

app/views/vacancies/new.html.erb
<h1>Nueva Vacante</h1>

<%= render 'form' %>

<%= link_to 'Atrás', vacancies_path, class: "btn btn-danger btn-xs"  %>

app/views/vacancies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ocupación:</strong>
  <%= Occupation.find_by_id(@vacancy.occupation_id).name %>
</p>

<p>
  <strong>Proyecto:</strong>
  <%= Project.find_by_id(@vacancy.project_id).name %>
</p>

<p>
  <strong>Descripción:</strong>
  <%= @vacancy.description %>
</p>

<p>
  <strong>Salario por Hora:</strong>
  <%= @vacancy.hourly_wage %>
</p>

<p>
  <strong>Horas Requeridas:</strong>
  <%= @vacancy.hours_required %>
</p>

<p>
  <strong>Estatus:</strong>
      <% if @vacancy.availability_status == 1%>
            <% result = "Disponible" %>
          <% else %>
            <% result = "No Disponible"%>
          <% end %>
          <%= result %>
</p>


<%= button_to "Aplicar", { :controller => "vacancies", :action => "apply"}, class: "btn btn-info" %>
<br>
<%= link_to 'Editar', edit_vacancy_path(@vacancy),  class: "btn btn-warning btn-xs"%> |
<%= link_to 'Atrás', vacancies_path, class: "btn btn-danger btn-xs" %>